params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    defer_summaries_sec: 0.001
    device: cpu
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: dflex
    gamma: 0.99
    grad_norm: 1.0
    kl_threshold: 0.008
    learning_rate: 3e-4
    lr_schedule: adaptive
    lr_threshold: 0.008
    max_epochs: 1500
    mini_epochs: 5
    minibatch_size: 2048
    mixed_precision: false
    multi_gpu: false
    name: df_traffic_pace_car_ppo
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: 64
    player:
      determenistic: true
      games_num: 12
      num_actors: 4
      print_stats: true
    ppo: true
    reward_shaper:
      scale_value: 0.01
    save_best_after: 50
    save_frequency: 100
    score_to_win: 20000
    seq_len: 4
    steps_num: 32
    summaries_interval_sec_max: 0.002
    summaries_interval_sec_min: 0.001
    tau: 0.95
    truncate_grads: true
  diff_env:
    MM_caching_frequency: 16
    episode_length: 1000
    name: TrafficSinglePaceCarEnv_D
    stochastic_env: true
  general:
    cfg: ./examples/cfg/ppo/traffic_single_pace_car/scenario_d.yaml
    checkpoint: Base
    gi_alpha: 0.1
    logdir: ./examples/logs/traffic_single_pace_car/scenario_d/ppo/01-31-2023-20-43-21
    no_time_stamp: false
    num_envs: 0
    play: false
    ppo_kl_threshold: 0.008
    ppo_lr_threshold: 0.008
    render: false
    rl_device: cuda:0
    seed: 1
    test: false
    train: true
  load_checkpoint: false
  load_path: nn/df_traffic_pace_car.pth
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 512
      - 64
      - 64
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
