params:
  algo:
    name: grad_a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    defer_summaries_sec: 0.001
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: dflex
    gamma: 0.99
    gi_params:
      actor_learning_rate: 2e-3
      betas:
      - 0.7
      - 0.95
      critic_iterations: 16
      critic_learning_rate: 5e-4
      critic_num_batch: 4
      lr_schedule: linear
      max_alpha: 0.1
      network:
        actor: ActorStochasticMLP
        actor_mlp:
          activation: elu
          units:
          - 256
          - 128
        critic: CriticMLP
        critic_mlp:
          activation: elu
          units:
          - 128
          - 128
      num_step: 32
      seed: 5
      target_critic_alpha: 0.995
    grad_norm: 1.0
    kl_threshold: 0.0001
    learning_rate: 3e-4
    lr_schedule: adaptive
    lr_threshold: 0.0001
    max_epochs: 2000
    mini_epochs: 5
    minibatch_size: 2048
    mixed_precision: false
    multi_gpu: false
    name: df_humanoid_grad_ppo
    normalize_advantage: false
    normalize_input: true
    normalize_value: false
    num_actors: 64
    player:
      determenistic: true
      games_num: 12
      num_actors: 4
      print_stats: true
    ppo: true
    reward_shaper:
      scale_value: 0.01
    save_best_after: 50
    save_frequency: 100
    score_to_win: 20000
    seq_len: 4
    steps_num: 32
    summaries_interval_sec_max: 0.002
    summaries_interval_sec_min: 0.001
    tau: 0.95
    truncate_grads: true
  diff_env:
    MM_caching_frequency: 48
    episode_length: 1000
    name: HumanoidEnv
    stochastic_env: true
  general:
    cfg: ./examples/cfg/grad_ppo/humanoid.yaml
    checkpoint: Base
    gi_max_alpha: 0.1
    logdir: ./examples/logs/humanoid/grad_ppo/01-20-2023-13-09-32
    no_time_stamp: false
    num_envs: 0
    play: false
    ppo_kl_threshold: 0.0001
    ppo_lr_threshold: 0.0001
    render: false
    rl_device: cuda:0
    seed: 5
    test: false
    train: true
  load_checkpoint: false
  load_path: nn/df_humanoid.pth
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 64
      - 64
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
