params:  
  diff_env:
    name: CartPoleSwingUpEnv
    stochastic_env: True
    episode_length: 240
    MM_caching_frequency: 4

  algo:
    name: grad_a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: nn/df_cartpole_swing.pth

  config:
    name: df_cartpole_swing_up
    env_name: dflex
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: False
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    lr_threshold: 0.008
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 150
    save_best_after: 50
    save_frequency: 100
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    steps_num: 240        
    num_actors: 1 # 32
    minibatch_size: 240 # 1920
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001

    # grad informed
    gi_alpha: 1.0
    gi_alpha_schedule: identity
    gi_step_num: 32
    
    player:
      # render: True
      determenistic: True
      games_num: 12
      num_actors: 4
      print_stats: True
