params:  
  diff_env:
    name: TestEnv
    stochastic_env: False
    episode_length: 10
    MM_caching_frequency: 1

  algo:
    name: grad_a2c_continuous_alpha

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0.0
        fixed_sigma: True
    mlp:
      units: [64, 64]
      activation: elu
      d2rl: False
      
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: nn/df_test.pth

  config:
    device: cpu
    name: df_test
    env_name: dflex
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: False
    normalize_value: False
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: False
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-3
    lr_schedule: constant
    lr_threshold: 0.008
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 200
    save_best_after: 50
    save_frequency: 100
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    steps_num: 32
    num_actors: 64
    minibatch_size: 2048
    mini_epochs: 64
    critic_coef: 4
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 0.0001

    defer_summaries_sec: 0.001
    summaries_interval_sec_min: 0.001
    summaries_interval_sec_max: 0.002

    # grad informed

    defer_summaries_sec: 0.001
    summaries_interval_sec_min: 0.001
    summaries_interval_sec_max: 0.002

    gi_params:      
      num_step: 32
      
    player:
      # render: True
      determenistic: True
      games_num: 12
      num_actors: 4
      print_stats: True
